"""rename_cohorts_to_trades_and_drop_planned_sm

Revision ID: 635978daf9e7
Revises: 99bac75c6b93
Create Date: 2025-09-13 00:58:25.585140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635978daf9e7'
down_revision: Union[str, None] = '99bac75c6b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop the planned_sm column from cohorts table
    op.drop_column('cohorts', 'planned_sm')
    
    # Step 2: Rename the cohorts table to trades
    op.rename_table('cohorts', 'trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Rename the trades table back to cohorts
    op.rename_table('trades', 'cohorts')
    
    # Step 2: Add back the planned_sm column
    op.add_column('cohorts', sa.Column('planned_sm', sa.Numeric(), nullable=False, server_default='0'))
    
    # Remove the server default after column creation
    op.alter_column('cohorts', 'planned_sm', server_default=None)
    # ### end Alembic commands ###
