"""Initial database schema

Revision ID: 99bac75c6b93
Revises: 
Create Date: 2025-09-12 19:13:06.461949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bac75c6b93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cashflow_snapshots', 'planned_sm',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'actual_sm',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('cashflow_snapshots', 'cumulative_payments',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'share_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'owed_this_month',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'cumulative_shared',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.drop_constraint(None, 'cashflow_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'cashflow_snapshots', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cohorts', 'planned_sm',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('cohorts', 'sharing_percentage',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('cohorts', 'cash_cap',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.create_unique_constraint('unique_company_cohort_month', 'cohorts', ['company_id', 'cohort_month'])
    op.drop_constraint(None, 'cohorts', type_='foreignkey')
    op.create_foreign_key(None, 'cohorts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('thresholds', 'minimum_payment_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.drop_constraint(None, 'thresholds', type_='foreignkey')
    op.create_foreign_key(None, 'thresholds', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thresholds', type_='foreignkey')
    op.create_foreign_key(None, 'thresholds', 'companies', ['company_id'], ['id'])
    op.alter_column('thresholds', 'minimum_payment_percent',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'])
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'cohorts', type_='foreignkey')
    op.create_foreign_key(None, 'cohorts', 'companies', ['company_id'], ['id'])
    op.drop_constraint('unique_company_cohort_month', 'cohorts', type_='unique')
    op.alter_column('cohorts', 'cash_cap',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('cohorts', 'sharing_percentage',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('cohorts', 'planned_sm',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'cashflow_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'cashflow_snapshots', 'companies', ['company_id'], ['id'])
    op.alter_column('cashflow_snapshots', 'cumulative_shared',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'owed_this_month',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'share_rate',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'cumulative_payments',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('cashflow_snapshots', 'actual_sm',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('cashflow_snapshots', 'planned_sm',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
