"""add_spends_table

Revision ID: 9b22936778d8
Revises: 635978daf9e7
Create Date: 2025-09-13 01:14:25.718485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b22936778d8"
down_revision: Union[str, None] = "635978daf9e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("cohort_month", sa.Date(), nullable=False),
        sa.Column("spend", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("spend >= 0", name="check_spend_positive"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "cohort_month", name="unique_company_spend_cohort_month"),
    )
    op.create_index(op.f("ix_spends_cohort_month"), "spends", ["cohort_month"], unique=False)
    op.create_index(op.f("ix_spends_id"), "spends", ["id"], unique=False)
    op.drop_index("ix_cashflow_snapshots_as_of_month", table_name="cashflow_snapshots")
    op.drop_index("ix_cashflow_snapshots_cohort_month", table_name="cashflow_snapshots")
    op.drop_index("ix_cashflow_snapshots_id", table_name="cashflow_snapshots")
    op.drop_table("cashflow_snapshots")
    op.drop_index("ix_cohorts_cohort_month", table_name="trades")
    op.drop_index("ix_cohorts_id", table_name="trades")
    op.create_index(op.f("ix_trades_cohort_month"), "trades", ["cohort_month"], unique=False)
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_cohort_month"), table_name="trades")
    op.create_index("ix_cohorts_id", "trades", ["id"], unique=False)
    op.create_index("ix_cohorts_cohort_month", "trades", ["cohort_month"], unique=False)
    op.create_table(
        "cashflow_snapshots",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.INTEGER(), nullable=False),
        sa.Column("cohort_month", sa.DATE(), nullable=False),
        sa.Column("as_of_month", sa.DATE(), nullable=False),
        sa.Column("planned_sm", sa.NUMERIC(), nullable=False),
        sa.Column("actual_sm", sa.NUMERIC(), nullable=True),
        sa.Column("cumulative_payments", sa.NUMERIC(), nullable=False),
        sa.Column("share_rate", sa.NUMERIC(), nullable=False),
        sa.Column("owed_this_month", sa.NUMERIC(), nullable=False),
        sa.Column("cumulative_shared", sa.NUMERIC(), nullable=False),
        sa.Column("at_cap", sa.BOOLEAN(), nullable=True),
        sa.Column("flip_100_active", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_cashflow_snapshots_id", "cashflow_snapshots", ["id"], unique=False)
    op.create_index("ix_cashflow_snapshots_cohort_month", "cashflow_snapshots", ["cohort_month"], unique=False)
    op.create_index("ix_cashflow_snapshots_as_of_month", "cashflow_snapshots", ["as_of_month"], unique=False)
    op.drop_index(op.f("ix_spends_id"), table_name="spends")
    op.drop_index(op.f("ix_spends_cohort_month"), table_name="spends")
    op.drop_table("spends")
    # ### end Alembic commands ###
