"""add_customers_table

Revision ID: e09193d9d276
Revises: 9b22936778d8
Create Date: 2025-09-13 12:07:11.506684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e09193d9d276"
down_revision: Union[str, None] = "9b22936778d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column("cohort_month", sa.Date(), nullable=False),
        sa.Column("spend_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["spend_id"], ["spends.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_cohort_month"), "customers", ["cohort_month"], unique=False)
    op.create_index("ix_customers_cohort_month_spend_id", "customers", ["cohort_month", "spend_id"], unique=False)
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_index("ix_customers_cohort_month_spend_id", table_name="customers")
    op.drop_index(op.f("ix_customers_cohort_month"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
